### ISSUE TITLE
textarea is limited to height 120px

### ISSUE THREAD

**Issue by parasquid** [Angelmmiguel/opalbox-jquery#1]
It would be awesome if:
- the texarea is automatically resized to the height of the initial content
- the textarea automatically resizes whenever the reader tries to play around with the content

I was trying to implement this through javascript but I never managed to do it :(

Any chance this can be part of the default themes that come with the plugin?

**Comment by Angelmmiguel** [comment]
Hello @parasquid,

Yes, I think I can develop new themes with full height ("light-full" and "dark-full"). Let me think about it ;)

Thanks for report this enhancement.

**Comment by Angelmmiguel** [comment]
Added to [v0.1.0](https://github.com/Angelmmiguel/opalbox-jquery/releases/tag/v0.1.0). Thanks :)
