### ISSUE TITLE
loader indicator when "Run" button is pressed

### ISSUE THREAD

**Issue by parasquid** [Angelmmiguel/opalbox-jquery#2]
Hello, I'm here again for another enhancement request :P

I've been implementing the opalbox plugin in my blog and have been converting some of my tutorial articles to use opalbox instead of writing down the expected answer in a comment.

It all works great on my fast Dell XPS 13 (2015) however when I was testing the article on my mobile phone, clicking the `Run` button will stall for a couple of seconds and then show the answer.

Having a loader indicator will result in an enhanced user experience.

**Comment by Angelmmiguel** [comment]
Hahaha, this is nice to improve the library ;)

It's a nice idea. I will add a CSS loader like [this](http://codepen.io/brunjo/pen/wBKmbm). Let me one week to implement these enhancements.

Happy 2016! :)

**Comment by Angelmmiguel** [comment]
Added to [v0.1.0](https://github.com/Angelmmiguel/opalbox-jquery/releases/tag/v0.1.0). Thanks :)
