### ISSUE TITLE
Opal.compile is not a function

### ISSUE THREAD

**Issue by parasquid** [Angelmmiguel/opalbox-jquery#3]
I wanted to start using Opal v0.8.1 in order to be able to use named parameters (see https://github.com/opal/opal/issues/678)

It gives me an error like this:

```
Uncaught TypeError: Opal.compile is not a function
$.extend.compile @ opalbox-jquery.min.js:10
$.extend.execute @ opalbox-jquery.min.js:10
(anonymous function) @ opalbox-jquery.min.js:10
m.event.dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4
```

Changing Opal back to 0.7.1 makes the plugin work again.

Will opalbox be supporting later versions of Opal?

**Comment by Angelmmiguel** [comment]
Hello @parasquid,

Yes, to update Opal to last stable version is the feature to set this library in v1.0.0. I will check how to import modules in new Opal versions.

Thanks!

**Comment by Angelmmiguel** [comment]
I modify the way to load Opal modules in the library. I only need to test it :)

**Comment by Angelmmiguel** [comment]
Done! Update the library to the last version. I set the version in the README to last stable version:

``` html

<!-- JS Dependencies (You can use CDN or local files) -->
<script type="text/javascript" src="http://cdn.opalrb.org/opal/0.8.1/opal.min.js"></script>
<script type="text/javascript" src="http://cdn.opalrb.org/opal/0.8.1/opal-parser.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<!-- JS File -->
<script type="text/javascript" src="<route to opalbox.jquery.min.js>"></script>
```

However, I think you can use `opalbox.jquery` 1.0.0 with newer beta versions of Opal.rb libraries.
